name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://kernel.org
    - name: Download
      run: wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.16.2.tar.xz

    # https://docs.kernel.org/admin-guide/README.html#installing-the-kernel-source
    - name: Install the kernel source
      run: |
        xz -cd linux-6.16.2.tar.xz | tar xvf -
        cd linux-6.16.2
        make mrproper

    # https://docs.kernel.org/admin-guide/README.html#build-directory-for-the-kernel
    - name: Configure and build the kernel
      run: |
        cd linux-6.16.2
        make defconfig
        make -j $(nproc)
        make INSTALL_MOD_PATH=${{ github.workspace }}/iso INSTALL_PATH=${{ github.workspace }}/iso/boot modules_install install
        ls -l ${{ github.workspace }}/iso/boot

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
