name: Makefile CI

env:
  VERSION: 6.16.2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache the kernel
      id: cache-kernel
      uses: actions/cache@v4
      with:
        path: linux-${{ env.VERSION }}
        key: linux-${{ env.VERSION }}

    # https://kernel.org
    - name: Download
      if: steps.cache-kernel.outputs.cache-hit != 'true'
      run: wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ env.VERSION }}.tar.xz

    # https://docs.kernel.org/admin-guide/README.html#installing-the-kernel-source
    - name: Install the kernel source
      if: steps.cache-kernel.outputs.cache-hit != 'true'
      run: |
        xz -cd linux-${{ env.VERSION }}.tar.xz | tar xvf -
        cd linux-${{ env.VERSION }}
        make mrproper

    - name: Install libelf-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libelf-dev

    # https://docs.kernel.org/admin-guide/README.html#build-directory-for-the-kernel
    - name: Configure and build the kernel
      run: |
        cd linux-${{ env.VERSION }}
        make defconfig
        make -j $(nproc)
        make INSTALL_MOD_PATH=${{ github.workspace }}/iso INSTALL_PATH=${{ github.workspace }}/iso/boot modules_install install
        ls -l ${{ github.workspace }}/iso/boot
